export const POKEMON_AVATARS = [
  { name: 'Bulbizarre', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png' },
  { name: 'Salamèche', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png' },
  { name: 'Carapuce', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png' },
  { name: 'Pikachu', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png' },
  { name: 'Rondoudou', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png' },
  { name: 'Miaouss', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png' },
  { name: 'Psykokwak', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png' },
  { name: 'Ectoplasma', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png' },
  { name: 'Magicarp', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png' },
  { name: 'Léviator', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png' },
  { name: 'Metamorph', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png' },
  { name: 'Évoli', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png' },
  { name: 'Ronflex', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png' },
  { name: 'Mewtwo', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png' },
  { name: 'Mew', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png' },
  { name: 'Carabaffe', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png' },
  { name: 'Tortank', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png' },
  { name: 'Reptincel', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png' },
  { name: 'Dracaufeu', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png' },
  { name: 'Herbizarre', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png' },
  { name: 'Florizarre', url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png' }
]

export const POKEMON_ANECDOTES = {
  'Bulbizarre': 'Bulbizarre ! Un Pokémon de départ très docile. Il adore faire la sieste au soleil pendant que sa graine grandit !',
  'Salamèche': 'Salamèche ! La flamme au bout de sa queue indique sa santé et sa force. Garde-la toujours bien allumée !',
  'Carapuce': 'Carapuce ! Sa carapace n\'est pas seulement protectrice, elle réduit aussi sa résistance à l\'eau pour nager très vite !',
  'Pikachu': 'Pikachu ! Il stocke de l\'électricité dans ses joues. S\'il est irrité, il peut libérer de puissantes décharges !',
  'Rondoudou': 'Rondoudou ! Ses yeux ronds fascinent sa cible avant qu\'il n\'entonne une douce berceuse qui endort tout le monde !',
  'Miaouss': 'Miaouss ! Il adore tout ce qui brille, en particulier les pièces de monnaie. C\'est un vrai petit rôdeur nocturne !',
  'Psykokwak': 'Psykokwak ! Il est constamment sujet à des maux de tête. Quand la douleur s\'accentue, il utilise d\'étranges pouvoirs psy !',
  'Ectoplasma': 'Ectoplasma ! Il se cache dans l\'ombre pour surprendre ses proies. Si tu ressens un frisson soudain, il est sûrement là !',
  'Magicarp': 'Magicarp ! On dit qu\'il est le Pokémon le plus faible au monde... Pourtant, sa ténacité et son évolution sont légendaires !',
  'Léviator': 'Léviator ! Un Pokémon d\'une brutalité incroyable. Il apparaît dans les récits de tempêtes pour tout détruire !',
  'Metamorph': 'Metamorph ! Il peut modifier sa structure moléculaire pour copier l\'apparence exacte de n\'importe quel Pokémon !',
  'Évoli': 'Évoli ! Son code génétique instable lui permet de s\'adapter et d\'évoluer de huit façons différentes !',
  'Ronflex': 'Ronflex ! Son estomac résiste à toutes les toxines. Il ne s\'arrête de dormir que pour manger des montagnes de nourriture !',
  'Mewtwo': 'Mewtwo ! Créé artificiellement par des scientifiques à partir de Mew. Son cœur est froid et son pouvoir psychique immense !',
  'Mew': 'Mew ! Un Pokémon fabuleux et extrêmement rare. On raconte qu\'il contient l\'ADN originel de tous les Pokémon !',
  'Carabaffe': 'Carabaffe ! Sa queue touffue est très prisée comme symbole de longévité. C\'est un nageur agile et très robuste !',
  'Tortank': 'Tortank ! Les canons à eau sur sa carapace peuvent percer l\'acier trempé. Un colosse des océans !',
  'Reptincel': 'Reptincel ! Il possède un tempérament bagarreur. Au combat, il lacère ses ennemis avec ses griffes acérées !',
  'Dracaufeu': 'Dracaufeu ! Ses ailes lui permettent de voler très haut. Il crache un feu si chaud qu\'il peut faire fondre la roche !',
  'Herbizarre': 'Herbizarre ! La force de ses pattes soutient le bourgeon sur son dos. Quand il est prêt à fleurir, il dégage un parfum doux !',
  'Florizarre': 'Florizarre ! Sa fleur s\'épanouit sous le soleil. Le parfum qui s\'en dégage apaise les Pokémon alentour.'
}
